### ISSUE TITLE
Question: Where I can find corresponding training videos ?

### ISSUE THREAD

**Issue by amrathesh** [tianocore-training/Presentation_FW#2]
Hi, 

I find many PDF slides in this repo for e.g, https://github.com/tianocore-training/Presentation_FW/blob/main/FW/Presentations/_B_01_EDK_II_Build_Processes_Pres.pdf 
But don't see corresponding video lectures, can anyone point me to them.

Thanks,
Amrathesh

**Comment by Laurie0131** [comment]
There are currently no videos available at this time.

**Comment by amrathesh** [comment]
Okay, Thank you Laurie.
